# Generated by Django 3.1.3 on 2020-11-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='full_image', verbose_name='Full size iamge')),
                ('image_mini', models.ImageField(blank=True, null=True, upload_to='mini_image', verbose_name='Image miniature')),
            ],
        ),
    ]
